services:
  ezxssdb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
    volumes:
      - "./ezxssdb:/var/lib/mysql"
    networks:
      - ezxss-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
  ezxss:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USE_MAIL_ALERTS=${useMailAlerts}
    expose:
      - 80
      - 443
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - ezxssdb
    environment:
      - INSTALL_CERTIFICATE=${autoInstallCertificate}
      - DOMAIN=${domain}
      - HTTPMODE=${httpmode}
    networks:
      - proxy
      - ezxss-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
networks:
  proxy:
    external: true
  ezxss-network:
    name: ezxss-network
    driver: bridge
